/*
 * This Java source file was generated by the Gradle 'init' task.

sh -c telnet rainmaker.wunderground.com 3000 | tee weather.txt


telnet rainmaker.wunderground.com | tee -a -i telnet.log



 */
package mud;



import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;

public class App {



    private final static Logger log = Logger.getLogger(App.class.getName());


    private void telnet() {



String s = "telnet rainmaker.wunderground.com | tee -a -i telnet.log";
log.info(s);

    }

    public static void main(String[] args) {
	new App().telnet();
    }
}
